-- Dữ liệu phòng mẫu (chạy sau schema.sql, chỉ chạy 1 lần)
insert into public.rooms (name,type,city,district,address,free_rooms,total_rooms,price_min,price_max,amenities,hot,discount) values
  ('KTX Cái Răng','Ký túc xá','Tp. Cần Thơ','Quận Cái Răng','P. Lê Bình',10,30,0.7,1,array['Giờ tự do']::text[],false,0),
  ('12 Trần Hưng Đạo','Căn hộ','Tp. Cần Thơ','Quận Ninh Kiều','P. Tân An',2,6,5,6.5,array['Có máy lạnh','Có ban công']::text[],true,0),
  ('56 Nguyễn Văn Cừ','Phòng trọ','Tp. Cần Thơ','Quận Ninh Kiều','P. An Khánh',8,25,1.5,2.5,array['Có máy lạnh','Có cửa sổ']::text[],false,0),
  ('70 Phú Lợi','Phòng trọ','Tỉnh Bình Dương','Thành phố Thủ Dầu Một','P. Phú Lợi',6,20,1.7,2.4,array['Có gác']::text[],false,10),
  ('Khu trọ VSIP','Phòng trọ','Tỉnh Bình Dương','Thành phố Thuận An','P. An Phú',20,60,1.5,2.2,array['Giờ tự do']::text[],false,0),
  ('15 Đại lộ Bình Dương','Phòng trọ','Tỉnh Bình Dương','Thành phố Thuận An','P. Lái Thiêu',12,40,1.8,2.8,array['Có cửa sổ','Nhận xe điện']::text[],true,0),
  ('30 Nguyễn Văn Linh','Phòng trọ','Tp. Đà Nẵng','Quận Thanh Khê','P. Thạc Gián',4,10,1.8,2.5,array['Nuôi thú cưng']::text[],false,15),
  ('102 Lê Duẩn','Phòng trọ','Tp. Đà Nẵng','Quận Hải Châu','P. Thạch Thang',6,18,2,3.2,array['Có máy lạnh','Có cửa sổ']::text[],false,0),
  ('45 Võ Nguyên Giáp','Căn hộ','Tp. Đà Nẵng','Quận Sơn Trà','P. Phước Mỹ',2,8,6,8,array['Có máy lạnh','Có ban công']::text[],true,0),
  ('KTX Mỹ Đình','Ký túc xá','Tp. Hà Nội','Quận Nam Từ Liêm','P. Mỹ Đình 1',8,40,1,1.4,array['Giờ tự do']::text[],false,20),
  ('88 Nguyễn Trãi','Phòng trọ','Tp. Hà Nội','Quận Thanh Xuân','P. Thượng Đình',4,15,2.2,3,array['Có máy lạnh']::text[],false,0),
  ('12 Ngõ 100 Kim Mã','Phòng trọ','Tp. Hà Nội','Quận Ba Đình','P. Kim Mã',5,20,2.5,3.5,array['Có cửa sổ','Có gác']::text[],false,0),
  ('25 Trần Duy Hưng','Căn hộ','Tp. Hà Nội','Quận Cầu Giấy','P. Trung Hòa',3,12,7,9,array['Có máy lạnh','Có ban công']::text[],true,10),
  ('560 Lê Trọng Tấn','Mặt bằng','Tp. Hồ Chí Minh','Quận Tân Phú','P. Tây Thạnh',1,4,14,14,array['Có ban công']::text[],false,0),
  ('119 Đường Số 4','Mặt bằng','Tp. Hồ Chí Minh','Quận Bình Tân','P. An Lạc',1,7,8,8,array['Có cửa sổ','Nhận xe điện']::text[],false,0),
  ('140/74 Lê Đức Thọ','Mặt bằng','Tp. Hồ Chí Minh','Quận Gò Vấp','P. 05',1,4,7,7,array['Có cửa sổ']::text[],false,0),
  ('35/19 Nguyễn Hữu Tiến','Ký túc xá','Tp. Hồ Chí Minh','Quận Tân Phú','P. Tây Thạnh',7,8,0.8,0.8,array['Giờ tự do']::text[],true,0),
  ('1/1A Tô Ký','Ký túc xá','Tp. Hồ Chí Minh','Quận 12','P. Trung Mỹ Tây',1,20,1.5,1.5,array['Có máy lạnh']::text[],false,0),
  ('28/55 Lương Thế Vinh','Ký túc xá','Tp. Hồ Chí Minh','Quận Tân Phú','P. Tân Thới Hòa',4,30,1.8,1.8,array['Có máy lạnh','Giờ tự do']::text[],false,25),
  ('150 Lakeview City','Căn hộ','Tp. Hồ Chí Minh','Quận 2','P. An Phú, Khu đô thị Lakeview City',1,10,6.5,6.5,array['Có máy lạnh','Có cửa sổ']::text[],false,0),
  ('219 Lakeview City','Căn hộ','Tp. Hồ Chí Minh','Quận 2','P. An Phú, Khu đô thị Lakeview City',2,10,6,7,array['Có máy lạnh','Có ban công']::text[],true,12),
  ('42-44 Phan Bá Vành','Căn hộ','Tp. Hồ Chí Minh','Thành phố Thủ Đức','P. Thạnh Mỹ Lợi',2,14,17,17,array['Có máy lạnh','Có ban công','Nhận xe điện']::text[],true,0),
  ('943/18 Quang Trung','Phòng trọ','Tp. Hồ Chí Minh','Quận Gò Vấp','P. 10',3,10,4.5,4.5,array['Có gác','Có cửa sổ']::text[],false,0),
  ('553/21 Lũy Bán Bích','Phòng trọ','Tp. Hồ Chí Minh','Quận Tân Phú','P. Phú Thạnh',1,1,5.5,5.5,array['Có máy lạnh','Nuôi thú cưng']::text[],false,10),
  ('120-122 Đường Số 18','Phòng trọ','Tp. Hồ Chí Minh','Thành phố Thủ Đức','KĐT Đông Tăng Long, P. Long Trường',22,22,4.8,9,array['Có máy lạnh','Có ban công','Có gác']::text[],true,0),
  ('G20 Đường 17 KDC Thanh Nhựt','Phòng trọ','Tp. Hồ Chí Minh','Huyện Nhà Bè','Xã Hiệp Phước',9,9,2.5,3.5,array['Có cửa sổ','Nuôi thú cưng']::text[],false,20),
  ('366/17N Lê Văn Quới','Phòng trọ','Tp. Hồ Chí Minh','Quận Bình Tân','P. Bình Hưng Hòa A',10,10,3,5,array['Có gác','Có cửa sổ','Giờ tự do']::text[],false,0),
  ('73 Hàng Tre','Phòng trọ','Tp. Hồ Chí Minh','Thành phố Thủ Đức','Mặt tiền Hàng Tre, P. Long Bình',25,31,4.1,5.3,array['Có máy lạnh','Có ban công','Nhận xe điện']::text[],true,15),
  ('92B Lâm Thị Hố','Phòng trọ','Tp. Hồ Chí Minh','Quận 12','Mặt tiền Lâm Thị Hố, P. Tân Chánh Hiệp',3,6,3,4,array['Có máy lạnh','Có cửa sổ']::text[],true,0);
